### ISSUE TITLE
Spatial weights

### ISSUE THREAD

**Issue by imarkonis** [imarkonis/ithaca#11]
Develop a function at geo_functions.R in ithaca/source for spatial aggregation with spatial weights for grid cell size. 

Input: data.table dt(lon, lat)
Output: vector with standardized areas, where 1 is the maximum

Can we use directly pRecipe?

**Comment by MiRoVaGo** [comment]
pRecipe has a function (make_ts) to internally compute weights to generate a time series but
input: .nc file path
output: .csv file with date, value, name, type
E.g.,
make_ts("era5_tp_mm_kenya_200101_201912_025_monthly.nc")
would generate the file era5_tp_mm_kenya_200101_201912_025_monthly_ts.csv
with columns:
date, value, name, type
2001-01-01, <value>, ERA5, Reanalysis
2001-02-01, <value>, ERA5, Reanalysis
.
.
.
2019-12-01, <value>, ERA5, Reanalysis

**Comment by imarkonis** [comment]
So we cannot use pRecipe..
