### ISSUE TITLE
Create global land datasets

### ISSUE THREAD

**Issue by imarkonis** [imarkonis/ithaca#13]
Apply the landmask function to all precipitation datasets and store them in server. 

Script should be saved in 04_land_mask. I copied the function in source/geo_functions, where all the corresponding functions will be stored.

**Comment by MiRoVaGo** [comment]
@Rajani462 
Data sets generated and staged for review under ~/shared/data_review/ithaca_#13

**Comment by Rajani462** [comment]
Reviewed; all the datasets seem cropped properly.

**Comment by MiRoVaGo** [comment]
Data sets have been moved from data_review into their respective location. I.e., data/obs/precip/raw/ and data/sim/precip/raw/
Issue can be closed now
