### ISSUE TITLE
prec_change :: datasets

### ISSUE THREAD

**Issue by imarkonis** [imarkonis/ithaca#164]
Add GSMaP at monthly/annual scale in database and fix JRA55 NA time bug.

**Comment by MiRoVaGo** [comment]
What caused the JRA-55 bug is still unclear, cdo -setreftime -settaxis didn't work.
Regenerating yearly from monthly fixed it.
GSMaP monthly was already in the server, yearly was added in the same folder (/shared/data/obs/precip/raw)
