### ISSUE TITLE
Add information for datasets in SI (overleaf)

### ISSUE THREAD

**Issue by imarkonis** [imarkonis/ithaca#62]
File: supporting_info.tex
Section: Text S1. Data set information

Add a table with datasets information consisting of columns: name, version, period, resolution, reference and fill it with information from Data & Methods in main.tex as well as in 
https://czuvpraze.sharepoint.com/:w:/t/czu-in6183d77113e12/ES7FxU7Uex1Lo776LBtyj_QBkxyjXnxqCBMph8hyL1B-Ig?e=wUlBzS

Add 2-3 sentences describing each dataset.

**Comment by imarkonis** [comment]
Pls also add citations in text. For example: The CMORPH is short for Climate Prediction Center morphing method (Joyce et al. 2004).

**Comment by SPratapIND** [comment]
Information updated.
